general.import = ["~/.config/alacritty/rose-pine.toml"]
general.live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 1.0
