local map = vim.keymap.set
local snacks = require("snacks")

map("n", "<leader>pv", "<cmd>Ex<cr>", { desc = "Explore files" })

map("v", "J", ":m '>+1<cr>gv=gv", { desc = "Move selection down" })
map("v", "K", ":m '<-2<cr>gv=gv", { desc = "Move selection up" })

map("n", "<C-d>", "<C-d>zz", { desc = "Half-page down" })
map("n", "<C-u>", "<C-u>zz", { desc = "Half-page up" })
map("n", "n", "nzzzv", { desc = "Next search result" })
map("n", "N", "Nzzzv", { desc = "Prev search result" })

map("x", "<leader>p", '"_dP', { desc = "Paste without yanking" })

map("n", "<leader>d", '"_d', { desc = "Delete without yanking" })
map("v", "<leader>d", '"_d', { desc = "Delete without yanking" })

map("n", "<leader>y", '"+y', { desc = "Yank to system clipboard" })
map("v", "<leader>y", '"+y', { desc = "Yank to system clipboard" })
map("n", "<leader>Y", '"+Y', { desc = "Yank line to system clipboard" })

map("n", "Q", "<nop>")

map("n", "<leader>bb", "<cmd>bprevious<cr>", { desc = "Previous buffer" })
map("n", "<leader>bn", "<cmd>bnext<cr>", { desc = "Next buffer" })

map("n", "<C-h>", "<cmd>TmuxNavigateLeft<cr>", { desc = "Tmux left" })
map("n", "<C-j>", "<cmd>TmuxNavigateDown<cr>", { desc = "Tmux down" })
map("n", "<C-k>", "<cmd>TmuxNavigateUp<cr>", { desc = "Tmux up" })
map("n", "<C-l>", "<cmd>TmuxNavigateRight<cr>", { desc = "Tmux right" })
map("n", "<C-\\>", "<cmd>TmuxNavigatePrevious<cr>", { desc = "Tmux previous" })

map("n", "<leader>ff", function()
  snacks.picker.files()
end, { desc = "Find files" })
map("n", "<leader>fb", function()
  snacks.picker.buffers()
end, { desc = "Find buffers" })
map("n", "<leader>fh", function()
  snacks.picker.recent()
end, { desc = "Find recent files" })
map("n", "<leader>fq", function()
  snacks.picker.qflist()
end, { desc = "Quickfix list" })
map("n", "<leader>a", function()
  snacks.picker.grep()
end, { desc = "Grep" })
map("n", "<leader>?", function()
  snacks.picker.commands()
end, { desc = "Commands" })
map("n", "<leader>fg", function()
  snacks.picker.git_files()
end, { desc = "Find git files" })
map("n", "gr", function()
  snacks.picker.lsp_references()
end, { desc = "References" })
map("n", "gi", function()
  snacks.picker.lsp_implementations()
end, { desc = "Implementations" })
map("n", "<leader>ls", function()
  snacks.picker.lsp_workspace_symbols()
end, { desc = "Workspace symbols" })
